my_string = input('Из какого Вы города: ')
print(len('My name is Irina'))
print(my_string .upper())
print(my_string .lower())
print(my_string .replace(' ', ''))
print(my_string [0])
print(my_string [-1])